config/routes.rb
DefaultSite::Application.routes.draw do
  scope 'admin' do
    resources :documents
    resources :images do
      collection { get :galleries }
    end
    resources :pages do
      resources :widgets
    end
    resources :nav_menus do
      resources :nav_items
    end
    resources :users do
      member do
        get :change_password
      end
    end
    match '/', :to => 'admin#home', :as => 'admin_home'

    post "/nav_menus/order_nav_items", :to => 'nav_menus#order_nav_items', :as => :order_nav_items
    post "/order_images", :to => 'images#order_images', :as => :order_images
    post '/order_widgets', :to => 'pages#order_widgets', :as => :order_widgets
  end
  
  resources :sessions, :only => [:create]

  match '/signin', :to => 'sessions#new', :as => :signin
  match '/signout', :to => 'sessions#destroy', :as => :signout
  
  post '/add_region', :to => 'pages#add_region', :as => :add_region
  
  # Routes in the host application
  get '/pages/:id', :to => 'pages#show', :as => :page_show
  match '/', :to => 'pages#show', :id => 'home', :as => :root
  
end

app/models/nav_menu.rb
class NavMenu
  include Mongoid::Document
  field :name
  field :menu_type
  field :slug
  
  has_many :nav_items
  #test
  
  validates_uniqueness_of :name
  before_create :generate_slug
  
  def generate_slug
    self.slug = name.gsub("'", "").parameterize('_')
  end

  def self.find_by_slug(slug)
    self.where(:slug => slug).first
  end  
  
  def order_nav_items(params)
    nav_items.each do |nav_item|
      nav_item.position = params['navitem'].index(nav_item.id.to_s) + 1
      nav_item.save!
    end
  end
  
  def max_position
    existing_nav_items = nav_items.select {|nav_item| !nav_item.position.nil?}
    current_highest = existing_nav_items.map(&:position).max
    current_highest ||= 0
  end  
  
  def self.admin_nav
    where(:menu_type => 'admin').first
  end

  def self.main_nav
    where(:menu_type => 'main_nav').first
  end
    
end

app/controllers/nav_menus_controller.rb
class NavMenusController < AdminController

  def index
    @nav_menus = NavMenu.all
  end

  def new
    @nav_menu = NavMenu.new
  end

  def edit
    @nav_menu = NavMenu.find(params[:id])
  end

  def create
    nav_menu = NavMenu.new(params[:nav_menu])
  
    if nav_menu.save
  		redirect_to nav_menus_path, :notice => "Successfully created navigation menu"
    else
      flash[:error] = "Nav Menu could not be created"
      render :action => "new"
    end
  end

  def update
    @nav_menu = NavMenu.find(params[:id])

    if @nav_menu.update_attributes(params[:nav_menu])
  		redirect_to nav_menus_path, :notice => "Successfully created navigation menu"
    else
      flash[:error] = "Nav Menu could not be updated"
      render :action => "edit"
    end
  end

  def destroy
    @nav_menu = NavMenu.find(params[:id])
    @nav_menu.destroy

    redirect_to nav_menus_path
  end
  
  def order_nav_items
    nav_menu = NavMenu.find(params[:id])
    nav_menu.order_nav_items(params)
    render :nothing => true
  end  


end

app/helpers/nav_menus_helper.rb
module NavMenusHelper

  def main_navigation
    NavMenu.main_nav || NavMenu.first
  end
          
end

app/views/nav_menus/_form.html.erb
<%= form_for @nav_menu do |f| %>
	<div class="field">
	  <%= f.label :name %>
	  <%= f.text_field :name %>
	</div>
	<div class="field">
	  <%= f.label :menu_type %>
	  <%= f.select :menu_type, options_for_select([['Admin', 'admin'],['Main Nav', 'main_nav'], ['Footer', 'footer']]) %>
	</div>

  <div class="button confirm_button">
    <%= f.submit :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/nav_menus/edit.html.erb
<div class="top_right_controls">
	<%= link_to 'New Nav Item', new_nav_menu_nav_item_path(@nav_menu), :class => 'btn btn-info' %>
</div>

<div class="page_header">
	<h1>Editing nav_menu</h1>
</div>

<section class="page_content">
	<%= render 'form' %>
</section>

app/views/nav_menus/index.html.erb
<div class="top_right_controls">
	<%= link_to 'New Navigation Menu', new_nav_menu_path, :class => 'btn btn-info' %>
</div>

<div class="page_header">
	<h1 class="header">Navigation Menus</h1>
</div>

<section class="page_content">
	<% @nav_menus.each do |nav_menu| %>
		<div class="index_item page_index_item">
			<div class="controls">
				<%= link_to 'Delete', nav_menu_path(nav_menu), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger' %>			
				<%= link_to 'Edit', nav_menu_nav_items_path(nav_menu), :class => 'btn btn-warning' %>			
			</div>
			<%= link_to nav_menu.name, nav_menu_nav_items_path(nav_menu) %>
		</div>
	<% end %>
</section>

app/views/nav_menus/new.html.erb
<div class="page_header">
	<h1>New nav_menu</h1>
</div>

<section class="page_content">
	<%= render 'form' %>
</section>